### ISSUE TITLE
Resize image when user crop image

### ISSUE THREAD

**Issue by matamune94** [Norserium/vue-advanced-cropper#13]
I really like your feature
but i have a question
I have an example: 
I have a picture with width and height : 1280 x 720
when the user finishes cropping . it maybe will 800 x 800 
but in fact that picture just have size is 300 x 300
this plugin can do that ?

**Comment by Norserium** [comment]
Hello!

I suppose, that it should not be the feature of this library, because it's quite complicated and rare task. You can use the special library to do it (for example [hermite-resize](https://github.com/viliusle/Hermite-resize))

It will be pretty hard to implement the resizing feature that satisfies all users because there is a plenty of different resizing algorithms and approaches.

**Comment by matamune94** [comment]
@Norserium thanks sir

**Comment by Norserium** [comment]
May I close the issue? Did you solve your problem or you need further help?

**Comment by matamune94** [comment]
> @matamune94, may I close the issue? Did you solve your problem or you need further help?

it working, i will close this issue , really thanks

**Comment by Norserium** [comment]
@matamune94, @lugodev, I've added the possibility to limit the result canvas size in `1.5.0` in the [`canvas`](https://norserium.github.io/vue-advanced-cropper/components/cropper.html#canvas) property.  Take a look at the real-time example in ["Resize the result"](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#resize-the-result) section.

**Comment by lugodev** [comment]
Great work @Norserium 👏👏👏
