### ISSUE TITLE
zoom using slider

### ISSUE THREAD

**Issue by vortechron** [Norserium/vue-advanced-cropper#131]
zoomFactor data bind with slider, but it seems not working, the zoom is not smooth. Cant find an example on how to implement it.

```
    watch: {
        zoomFactor(value, old) {
            if (old > value) {
                this.$refs.cropper.zoom(0.5)
            } else {
                this.$refs.cropper.zoom(2)
            }
        }
    },
```

**Comment by Norserium** [comment]
@vortechron, I assume, that the problem in the transitions, that obviously are not needed in your case.
```html
<cropper 
    :src="image"
    :transitions="false"
/>
```
By the way, creating the zoom slider is not a trivial task, because the cropper doesn't has the absolute zoom, it has only the relative zoom. It's deliberate decision because it's obviously unclear what's `1` or `0.5` zoom for different images and different restrictions that could be customized.

So at least now you should define yourself what is the absolute zoom. 

Luckily, I've created [the example that reproduces the Twitter cropper with the slider](https://codesandbox.io/s/vue-advanced-cropper-twitter-suoyc?file=/src/App.vue) before, so you can just copy-paste my logic.

**Comment by vortechron** [comment]
perfect, just what I need! tq man @Norserium
