### ISSUE TITLE
canvas.toDataURL doesn't respect stencil

### ISSUE THREAD

**Issue by andreasvirkus** [Norserium/vue-advanced-cropper#23]
Hi, thanks for an awesome component! The docs are great and the component is very easy to use 💯 

I have an issue with calling 
```
const { canvas } = this.$refs.cropper.getResult()

this.$emit("submit", canvas.toDataURL())
```

with both the default `CircleStencil` and the advanced stencil example. The result is always a rectangle with full corners.

I've also created a replication here:

https://codesandbox.io/s/vue-sc4k6

![croppa-small](https://user-images.githubusercontent.com/9140811/70085666-5d16f300-1619-11ea-827f-0622358d58da.gif)

My current workaround is to apply a small border radius to the image that displays the result, but ideally (especially with maybe changing the stencil in the future), I'd like a way to get the image cropped by the stencil 🙏

**Comment by Norserium** [comment]
Hello, @andreasvirkus!

Unfortunately, it's not possible by the means of this library, because the stencil just define the rectangle area that will be cropped. Moreover, it's pretty often practice to crop a square by the circle stencil.

But you can anyway process a square canvas to get the needed result (if you want to use this method, test it on different browsers before to use one in production):
https://codesandbox.io/s/vue-xeb59

**Comment by andreasvirkus** [comment]
Well, that seems to work perfectly! 🎉 Thank you so much, my _canvas-fu_ was too weak for this

**Comment by Norserium** [comment]
You are welcome!

**Comment by yellow1912** [comment]
This is greate content, please add it to the document if you can. It will save people like me tons of time digging the old issues.

**Comment by Norserium** [comment]
@yellow1912 , I will try to think out how to place it in the documentation, because the mentioned issues are still edge cases.
