### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by denshest** [Norserium/vue-advanced-cropper#4]
Hello! Your plugin are very usefull but I have a problem. My Vuejs project listen `8000` port on `localhost`, and API listen `8001`. I get this error when I want to get my image from Database:
```
Access to image at 'http://127.0.0.1:8001/uploads/page_images/5d3f7f3270844593066656.jpeg' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by Norserium** [comment]
Hello! 

I suppose, that this problem is not specific to this library. 

Add `<img src="http://127.0.0.1:8001/uploads/page_images/5d3f7f3270844593066656.jpeg"></img>` to your page to test it. If it appears, then I might be wrong.

If it doesn't appear, you should check your CORS settings on your server. It should allow cross domain requests at least for that images.

**Comment by denshest** [comment]
Thanks @Norserium for your reply!
But I’m already check it. Image loading with <img src=...> but not loading if I use src in <Cropper>

**Comment by Norserium** [comment]
Does you have any errors in the console? Could you provide the screenshot of them?

**Comment by Norserium** [comment]
By the way, what a version of this library do you use?

**Comment by denshest** [comment]
I'm using a `"vue-advanced-cropper": "^0.8.3"` version.
Image loading with my 
`
<image href="http://127.0.0.1:8001/uploads/page_images/5d3f7f3270844593066656.jpeg"
                           xlink:href="http://127.0.0.1:8001/uploads/page_images/5d3f7f3270844593066656.jpeg"
                           preserveAspectRatio="xMinYMin"
                           image-rendering="optimizeQuality" ref="image"></image>
`

But not loading via 

`
<Cropper src="http://127.0.0.1:8001/uploads/page_images/5d3f7f3270844593066656.jpeg"
                 :stencil-props="{
                    aspectRatio: aspectRatio,
                }" @change="onChanged"/>
`

![Снимок экрана от 2019-07-30 12-51-31](https://user-images.githubusercontent.com/15803481/62119716-d0ee6b00-b2c8-11e9-8a85-88b45a40e883.png)

**Comment by denshest** [comment]
With my `svg->image` its work perfectly 

![Снимок экрана от 2019-07-30 12-52-53](https://user-images.githubusercontent.com/15803481/62119784-fe3b1900-b2c8-11e9-8139-b2a36064aa98.png)

**Comment by Norserium** [comment]
I suppose, that the problem is occurred during placing the image at the hidden `canvas` element due security concerns. 

This problem is described here:
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#Storing_an_image_from_a_foreign_origin

So you can to add `Access-Control-Allow-Origin` header to your server responses now as a temporary solution.

I will try to reproduce your environment lately and investigate this problem more detail.

**Comment by denshest** [comment]
It’s header already sends from my Symfony 4 backend. It works because I can use my API and give image with [img src..]
I think that problem with this library and getting image from remote server without request header
Thank you, for your reply. I will wait you

**Comment by Norserium** [comment]
Could you provide the screenshot of response headers?

Example (from network tab of Chrome)
![image](https://user-images.githubusercontent.com/9862719/62123615-fd0dea00-b2d0-11e9-8123-faf20713df71.png)

**Comment by denshest** [comment]
Response header what?
Getting image from img src?

**Comment by Norserium** [comment]
Yes

**Comment by denshest** [comment]
![image](https://user-images.githubusercontent.com/15803481/62125220-33e5ff00-b2d5-11e9-9748-c3ce248579b6.png)

**Comment by Norserium** [comment]
The response headers doesn't contain `access-control-allow-origin` header. That's problem. If I even put this image at canvas, one becomes tainted and you will not be able to call `toDataURL` method on it.

But if you need to get only coordinates of cropped area, then it's possible event without that headers. In this case I should make some fixes.

**Comment by denshest** [comment]
I want to use coordinates for my svg and I want to show preview with cropper)

I think I don't need the `toDataURL`

**Comment by Norserium** [comment]
Then give me some time please. I should choose the best way to implement fixes.

**Comment by Norserium** [comment]
Update to `0.9.0` and add `:canvas="false"` attribute to your cropper

**Comment by denshest** [comment]
Thank you! I will check it soon.

**Comment by denshest** [comment]
![image](https://user-images.githubusercontent.com/15803481/62133655-d1e2c500-b2e7-11e9-8e68-9aa122633ed3.png)

All works, thank you!
What about `@types/vue-advanced-cropper`? :)

**Comment by Norserium** [comment]
> What about @types/vue-advanced-cropper? :)

I will consider it. Maybe I even rewrite this library to Typescript someday.

> All works, thank you!

You are welcome!

**Comment by Norserium** [comment]
@denshest, I assume, that in new versions of this library (0.11.0 and higher) you should set `checkOrientation` to `false` in your case, because to check an orientation of image the library needs access to an image content (the access is denied due your CORS settings).

**Comment by woliveirac** [comment]
Hello there!

@Norserium 

I'm facing this problem at the moment and i just wanna check what should i do. 

I have CORS enabled on my server, only requests coming from an exactly origin can read my image. 

In this case, the library is doing a request without the proper header set which should fix the problem. 

The "check-orientation" didn't work for me, but, canvas set to false did, however, i don't know what the side consequences of that will do, also, i have errors on my console saying that the canvas is undefined, but, it's working.

Would it be possible to add an option to include headers when the library make the image request? 

Because that would solve the problem ...

Working code:

![image](https://user-images.githubusercontent.com/7048196/75709610-c69eb000-5ca1-11ea-803e-01f7d17bbe5a.png)

If i remove the canvas option, it doesn't load the image.


Best regards and amazing library.

**Comment by Norserium** [comment]
Hello, @woliveirac! 

> I can't get the result image if i set canvas to false, right?

Yes, you can't. It's not the limitation of my library, it's the browser's limitation. If you have got no 'Access-Control-Allow-Origin' in the image loading response header, you can't get the access to content of the canvas (it will be tainted).

Could you provide the url of the page where the cropper is placed and the url of image?
