### ISSUE TITLE
Nuxt integration

### ISSUE THREAD

**Issue by dminchev** [Norserium/vue-advanced-cropper#51]
I'm using the library with regular Vue application without any problems. 

Now I'm integrating the library in a nuxt application, however passing :src="imageUrl" does not assign to the `src` property but as `data-src` - check the screen shot https://take.ms/ZlgyZ

```
<VueCropper ref="cropper" class="cropper" :check-cross-origin="false" :src="imageUrl" />
```

I'm able to set the src using refs, but this is incorrect property mutation
```
this.$refs.cropper.src = value
```

**Comment by dminchev** [comment]
OK, I've found a solution using `:src.sync="imageUrl"` which resolves my issues.

**Comment by Norserium** [comment]
@dminchev, @leadbro, @CavalcanteLeo did you use [`nuxt-lazy-load`](https://www.npmjs.com/package/nuxt-lazy-load) library in your projects?

During the investigation I've found that this library uses `string-replace-loader` internally. This library replaces strings in the contents loaded by the loader.

The rules are [here](https://gitlab.com/broj42/nuxt-lazy-load/-/blob/master/lib/module.js#L33):
```js
stringReplaceLoaderOptions = [
  {search: '( )src=', replace: ' v-lazy-load data-src=', flags: 'g' },
  {search: '(:)src=', replace: 'v-lazy-load :data-src=', flags: 'g' },
  {search: '( )srcset=', replace: ' v-lazy-load data-srcset=', flags: 'g' },
  {search: '(:)srcset=', replace: 'v-lazy-load :data-srcset=', flags: 'g' },
  {search: '( )poster=', replace: ' v-lazy-load data-poster=', flags: 'g' },
  {search: '(:)poster=', replace: 'v-lazy-load :data-poster=', flags: 'g' },
]
```

As you see, every string `src=` and `:src=` are replaced by some other strings. It explains why @dminchev workaround may work: the attribute `src.sync` simply was not replaced by this loader, because it doesn't match to the rules above.

The solutions:
1. You can use `directiveOnly` option. In this case you should set `v-lazy-load` explicitly on `img`, `video` and other tags.
2. You can use the workaround above and set `src` to `src.sync`.
