### ISSUE TITLE
Bootstrap modal is closed when cursor is released outside the modal

### ISSUE THREAD

**Issue by h0rseduck** [Norserium/vue-advanced-cropper#63]
![cropper](https://user-images.githubusercontent.com/4640238/87690234-9f550500-c7a2-11ea-9dd3-8bd328f17701.gif)

Version: 0.16.6

Bootstrap Vue: 2.15.0
Bootstrap: 4.4.1

https://jsfiddle.net/h0rseduck/qb63wsvg/

**Comment by Norserium** [comment]
Hello, @h0rseduck! 

The problem is that cropper stops an event propagation on its elements click. It breaks the click-out algorithm of the bootstrap dialog window, because to determine that user clicked inside modal it process all `mousedown` events on the dialog window and remember this fact until `mouseup` event occurs.

But the story is not without hope, there is [a workaround](https://jsfiddle.net/eqjzuak6/).

**Comment by h0rseduck** [comment]
Hello, @Norserium!

Thanks for response and for the great component!
