### ISSUE TITLE
 the stencyl, cut the image area?

### ISSUE THREAD

**Issue by karelbyte** [Norserium/vue-advanced-cropper#68]
Hello, a newbie question, if I use the circle-stencil, it is assumed that the image that will save me is what is inside the circle, but it still saves me a rectangle, shouldn't it be a circle? Am I doing it wrong? Or do I have a misconception? Or that sole round contour is to select, can you get me out of my doubt?

**Comment by Norserium** [comment]
Hello, @karelbyte!

The stencil always defines only the rectangle area to crop (it is able to limit maximum and minimum aspect ratios only). It's the intentional decision, because there are plenty of situations where circle stencil, for example, is used to get the square image.

But you can crop the result by yourself. I've wrote [the example](https://codesandbox.io/s/vue-xeb59) before for the similar question. You can use it, but before the using in production you should test it on different browsers.

Please change the title of the issue to help other users to find your question in the future.

**Comment by Norserium** [comment]
@karelbyte, did you solve your problem?

**Comment by karelbyte** [comment]
Yes, with the provided example, it worked perfect! Thank you

**Comment by Norserium** [comment]
@karelbyte, I'm glad to hear it! I close issue then.
