### ISSUE TITLE
Programmatically maximise cropper

### ISSUE THREAD

**Issue by chris-copleston** [Norserium/vue-advanced-cropper#7]
Hi Norserium, thanks for sharing such as great component!

Is it possible to programmatically set the crop region? I am trying to implement a button that maximises it so it is easy to include all the image without dragging out the handles.

**Comment by Norserium** [comment]
Hello! 

Currently it's not allow. 

But as a workaround you can call internal methods (it's workaround, because it's not documented approach and may be unavailable in future releases):
1. You can call `onChangeCoordinates(coordinates)` method, that is called internally to set coordinates. But it will not check if passed coordinates are allowed, so strange things may happen.
2. You can call `onResize(resizeEvent)` events to simulate [resize event](https://norserium.github.io/vue-advanced-cropper/events/resize-event.html).

Anyway, I will think about adding the appropriate method.

I suppose it will be `setCoordinates(coordinates)`, where coordinates is an object like `{left: 10, top: 25, width: 150, height: 200}`, that will produce appropriate resize and move events.

**Comment by chris-copleston** [comment]
Hey Norserium, that sounds like a great enhancement.

I look forward to it, many thanks!

**Comment by Norserium** [comment]
I've updated the documentation, please read [this section](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#set-coordinates). If you have questions to API, feel free to ask them.

I'm currently testing this method, and after that I will release `0.12.0`.

**Comment by Norserium** [comment]
@chris-copleston, I've released `0.12.0`. Please update to this version and check this feature.

**Comment by chris-copleston** [comment]
Not only an outstanding and well though out solution, but extremely well documented too! 

Many thanks Norserium!
