### ISSUE TITLE
Rotation Bugs on iOS?

### ISSUE THREAD

**Issue by warkior** [Norserium/vue-advanced-cropper#8]
Hi there,

I have been playing to Cropper trying to get it working for site users to upload profile images. I like the package a lot and have found it quite useful. We have found in some cases though, specifically with images loaded from iOS, the rotation is wrong when displayed in the preview window.

It may be due to PNG images having some other sort of alternate EXIF info. Not sure. 
We are using the code you posted here to upload the initial image.
https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#upload-image

Once the image is cropped, we then save the result to a file. The saved result then seems to have the correct orientation however the cropped image seems wrong.

Any thoughts on how we might fix this? I'm not sure if it is something we can change or if it is a bug in vue-advanced-cropper.

**Comment by rickkettner** [comment]
To add to this, I'm able to reproduce this issue with both an iPad and iPhone in a predictable way.  The rotation of the photo, when displayed in the cropping interface, is dependent on the rotation of the iOS device when it took the photo.  Even if the photo appears correctly on the iOS device, it will rotate 90 degrees to the left or right, or even appear upside down... all in a predictable way based on how the photo was taken (and the orientation of the iOS device).

Note: This issue is strictly during the preview/cropping process.  Once the image is processed the final output image has the correct rotation but, because the preview image was rotated during preview, the crop is applied to the incorrect portion of the image unless it's dead center (which would be the same spot on the image regardless of rotation).

Here is a link that may be helpful.  The problem appears to be that the preview image during the cropping process is ignoring the rotation data from iOS.

https://stackoverflow.com/questions/22308921/fix-ios-picture-orientation-after-upload-php

Would love to see this resolved as this cropping tool is really great.

**Comment by Norserium** [comment]
Thanks for the detail description of the probable bug. Could you provide the image that causes bug for tests?

**Comment by rickkettner** [comment]
@Norserium - Excellent questions.

The bug is consistently reproducible on both Safari and Chrome on iOS.  Both iPad and iPhone.

The version of the library we are using is "0.11.0".

Unfortunately I cannot provide an image for testing, because the issue appears to be tied directly to the image picker on iOS.  If I export the image via iPhoto or other means, it is converted into a JPEG that works perfectly on a Mac.  But uploading directly from iOS (either by taking a photo for immediate upload OR selecting one from the library of previously taken images) results in the rotation issue depending on the rotation of the phone at the time the photo was taken.

As best as I can tell, images that are stored directly in the iOS photo library display correctly but deep down are stored based on how they were taken at the time of the photo (rotation of the device, front or rear camera) and the meta data is used to display it correctly.  Exporting or displaying the photo seems to account for this data, so rotation is correct.  But for some reason the cropper preview is not accounting for the data, while the final cropped image is.

I hope that all made sense.  It's highly reproducible, but also somewhat confusing to explain, so don't hesitate to let me know if you have any more questions.

**Comment by Norserium** [comment]
There is a catch, I don't have iOS devices right now, so me need some help to investigate and solve this problem.

Could you test uploading at [the documentation](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#upload-image) now? Screenshots of the uploading process will be useful.

**Comment by rickkettner** [comment]
Surprisingly, I'm unable to reproduce the issue by using the uploader in your documentation.  So we updated to 0.12.0 to see if that would resolve it, and it did not.  I guess something about our implementation is causing the issue.  Not sure what though.

**Comment by warkior** [comment]
Hi Norserium.

Thanks for helping us with this. We have upgraded to 0.12.1 with no change in the issue. It seems to work fine on my Android device. Just has some issues on the iOS devices.  I'm attaching the relevant code that we are using. I think it's pretty close to what you had in your examples. We are doing this inside a Vue component.

In the methods we have:
```
uploadImage(event) {
	// Reference to the DOM input element
	var input = event.target;
	// Ensure that you have a file before attempting to read it
	if (input.files && input.files[0]) {
		// create a new FileReader to read this image and convert to base64 format
		var reader = new FileReader();
		// Define a callback function to run, when FileReader finishes its job
		reader.onload = (e) => {
			// Note: arrow function used here, so that "this.imageData" refers to the imageData of Vue component
			// Read image as base64 and set to imageData
			this.image = e.target.result;
		};
		// Start the reader job - read file as a data url (base64 format)
		reader.readAsDataURL(input.files[0]);
	}
}
```

In template portion:
```
<template>
  <div class="upload-example">
    <Cropper
        classname="upload-avatar"
				:stencilComponent="$options.components.CircleStencil"
        :src="image"
				ref="cropper"
				:stencilProps="{
		handlers: {
			eastNorth: true,
			north: false,
			westNorth: false,
			west: false,
			westSouth: false,
			south: false,
			eastSouth: false,
			east: false,
		}
	}"
    />
    <div class="button-wrapper">
			<span class="button" @click="$refs.file.click()" :disabled="saving === 1">
				<input type="file" ref="file" @change="uploadImage($event)" accept="image/*">
				Upload Image
			</span>
			<span class="button" v-if="image" :disabled="saving === 1" @click="saveImage()">
				Save
			</span>
    </div>
  </div>
</template>
```

And data:
```
data() {
	return {
		saving: 0,
		coordinates: {
			width: 0,
			height: 0,
			left: 0,
			top: 0
		},
		image: null
	}
},
```

**Comment by Norserium** [comment]
> Surprisingly, I'm unable to reproduce the issue by using the uploader in your documentation.

It's good news, because the documentation uses the new **not released** version. Could you test it more detail?

**Comment by rickkettner** [comment]
Yes I can test with more detail.  What would you like me to do?

**Comment by Norserium** [comment]
Just experiment with different photos, images and etc. and iOS devices. I'm preparing the new release now.

**Comment by rickkettner** [comment]
Okay, will do some testing now.

**Comment by Norserium** [comment]
Could you test uploading photos and images at [this example](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#custom-restrictions)? This widget allows you to test the cropping canvas by clicking `Download result`.

**Comment by rickkettner** [comment]
Okay, I tested the documentation one on iPad and iPhone with multiple browsers.  Will use that link to do further tests now.

**Comment by rickkettner** [comment]
Okay, that widget also seems to work correctly.  Tested on iPhone with Safari and Chrome, and then on iPad with Safari.  Previewing photos and downloading the result all worked as expected.

**Comment by Norserium** [comment]
I've published the new version `0.12.2`. Please update to this version.

**Comment by rickkettner** [comment]
@Norserium - Thank you for your help!  That seems to have resolved the issue for us.  I appreciate the quick replies and this fix.

**Comment by Norserium** [comment]
You are welcome! Thanks for testing!

**Comment by Norserium** [comment]
@rickkettner, @warkior, thanks for information about the bug and testing!
